version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      - MYSQLDB_USER=${MYSQLDB_USER}
      - MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}
      - MYSQLDB_DATABASE=${MYSQLDB_DATABASE}
      - MYSQLDB_HOST=database
      - MYSQLDB_PORT=${MYSQLDB_DOCKER_PORT}

    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: