services:
  mysqldb:
    platform: linux/amd64
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "4321"
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQLDB_ROOT_PASSWORD"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: app-service
    build:
      context: .
    env_file: ./.env
    ports:
      - "8080:8088"
      - "5005:5005"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:$5432/$MYSQLDB_DATABASE",
        "spring.datasource.username": "root",
        "spring.datasource.password": "4321",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect"
      }',
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
