services:
  mysqldb:
    platform: linux/amd64
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - "5434:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQLDB_ROOT_PASSWORD"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    image: app-service
    build:
      context: .
    env_file: ./.env
    ports:
      - "8080:8088"
      - "5005:5005"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "$DB_URL_ADDRESS",
        "spring.datasource.username": "$MYSQLDB_USER",
        "spring.datasource.password": "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect": "$HIBERNATE_DIALECT"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
